name: es-playground

include:
  - elasticsearch/compose.yaml
  - php-client/compose.yaml

services:
  rally:
    image: elastic/rally
    container_name: rally
    volumes:
      - rally-data:/rally/.rally:rw

networks:
  default: {}

volumes:
  rally-data:
